version: '3.8'

networks:
  analytics_net:
    driver: bridge

services:
  #PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: weather_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-db.d/DB.sql
    networks:
      - analytics_net
  
#Генератор данных
  data-generator:
    image: python:3.11-slim
    container_name: weather_generator
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./scripts:/app
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt &&
             python data_generator.py"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: weather_db
      DB_USER: weather_user
      DB_PASSWORD: weather_pass
    networks:
      - analytics_net

volumes:
  postgres_data: